### ISSUE TITLE
error: cannot find symbol

### ISSUE THREAD

**Issue by grozanov-dev** [privacysandbox/measurement-simulation#5]
Can i, as an adtech, create my own testdata based on my event logs? How, if yes?

**Comment by suriheemanshu** [comment]
Yes, you can play around with the simulation library with your own data. The format of your testdata should be same as what we have provided in our [testdata](https://github.com/privacysandbox/measurement-simulation/blob/main/testdata) directory:

<Year>/<Month>/<Date>: A .json file to list all your source events which were registered on that date as json data and another .json file to list all trigger events for that date.

The schema of your Source and Trigger json objects should match with our testdata examples.

Please refer to [Overview.md](https://github.com/privacysandbox/measurement-simulation/blob/main/OVERVIEW.md) for more details.

I can check with my team if we can build a data generator script which can convert your events logs to our expected input data schema. Feel free to share details about what you would expect from such script [here](https://issuetracker.google.com/issues/new?component=1116743&template=1629474)

**Comment by danghle** [comment]
HI @grozanov-dev, does the answer from @suriheemanshu address your concerns? If not, please feel free to reopen this ticket.
